import { Document, PaginateResult } from 'mongoose'

// Generated by https://quicktype.io

export interface IUser {
  memberTypeId: IMemberTypeID
  walletId: string
  verificationCode: null
  balance: number
  isVerified: boolean
  card: string
  pin: string
  name: string
  gender: string
  address: string
  phone: string
  cityId: ICityID
  identityNumber: string
  email: string
  username: string
  photoProfile: string
  joinDate: string
  portion: number
  wallet: IWallet
  bonus: IBonus
  notStandartUsername: any[]
}

export interface IBonus {
  class: string
  total: number
  statString: string
}

export interface ICityID {
  provinceId: IProvinceID
  name: string
}

export interface IProvinceID {
  name: string
}

export interface IMemberTypeID {
  name: string
  labelClass: string
  epaymentCutoffPrice: number
}

export interface IWallet {
  balance: number
}

export interface IUserModel extends IUser, Document {}

export interface IUserModelPaginate extends PaginateResult<IUserModel> {}
